with unreadable or nonexistent file checks

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -95,7 +95,7 @@ multiply(){
 # check for correct number of arguments (1 or 2 for dims, transpose, and mean since they can also take stdin, and 3 for
 # add and multiply, since they must take in 2 files and can't use stdin). If there's an incorrect number of arguments,
 # send error message to stderr and return 1 (a non-zero number), otherwise call the appropriate function.
-if [ "$#" = "1" ] || [ "$#" = "2" ]  
+if [ "$#" = "1" ]
 then
 	if [ "$1" = "dims" ] || [ "$1" = "transpose" ] || [ "$1" = "mean" ]     
 	then
@@ -104,11 +104,32 @@ then
 		echo "error: invalid number of arguments" 1>&2
 		exit 1
 	fi
+elif [ "$#" = "2" ]
+then
+	if [ "$1" = "dims" ] || [ "$1" = "transpose" ] || [ "$1" = "mean" ]     
+	then
+		if [[ -s $2 && -r $2 ]]
+		then
+			$1 "${@:1}"
+		else
+			echo "error: file does not exist or is not readble" 1>&2
+			exit 1
+		fi
+	else
+		echo "error: invalid number of arguments" 1>&2
+		exit 1
+	fi
 elif [ "$#" = "3" ]
 then
 	if [ "$1" = "add" ] || [ "$1" = "multiply" ]  
 	then
-		$1 "${@:2}"
+		if [[ -s $2 && -r $2 ]] && [[ -s $3 && -r $3 ]] 
+		then
+			$1 "${@:2}"
+		else
+			echo "error: file does not exist or is not readble" 1>&2
+			exit 1
+		fi
 	else
 		echo "error: invalid number of arguments" 1>&2
 		exit 1
