fixed spelling

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -343,7 +343,7 @@ then
 		then
 			$1 "${@:2}"
 		else
-			echo "error: file does not exist or is not readble" 1>&2
+			echo "error: file does not exist or is not readable" 1>&2
 			exit 1
 		fi
 	else
